---
 
- name: playbook-1
  connection: network_cli
  gather_facts: false
  hosts: all
  tasks:
 
    - name: Get config 
      ios_facts:
        gather_subset: all
 
    - name: Display the message
      debug:
        msg: "The  {{ ansible_net_hostname }} has has  {{ ansible_net_iostype }}  platform"