---
- name: "Playbook: Configure Banner MOTD and Login" 
  gather_facts: false
  hosts: all
  tasks:
    - name: "T1: Configure Banner MOTD"
      ios_banner:
        banner: motd 
        text: |
          Wellcome to the {{ inventory_hostname }}
        state: present

    - name: "T1: Configure Banner Login"
      ios_banner:
        banner: login 
        text: |
          Only Autorized Personal Allowed
        state: present
