---
- name: "Playbook: Configure Banner $ http server"
  connection: network_cli
  gather_facts: false
  hosts: switch 

  tasks:
    - name: "T1: Configure Banner MOTD $ http server"
      ios_config:
        lines:
          - no ip http server
          - no ip http secure-server
          - banner motd &**********THIS IS ROUTER - DO NOT MAKE CHANGES UNLESS AUTHORISED! YOU WILL BE PROSECUTED! **********&

      register: print_output

    -  debug: var=print_output