---
- name: iOS Config Commands
  hosts: switch
  gather_facts: false

  tasks:
    - name: configure and capture in variable
      ios_config:
        lines:
          - vlan 100
          - name 100
      register:
        ios_config_output
    - debug:
        var: ios_config_output
    
    - name: wr and capture in variable
      ios_command:
        commands:
         - wr
      register:
        ios_command_output
    - debug:
        var: ios_command_output.stdout_lines
        