---
- name: IOS Show Commands
  hosts: switch
  gather_facts: false
  
  tasks:
    - name: ios show commands for switch
      ios_command:
        commands:
          - show version | i IOS
          - show run | i hostname
      register: output
      
    - debug:
        var: output


