---
# Playbook to demonstrate looping over lists and dictionaries
- name: Loop over a list
  hosts: distribution
  gather_facts: false
  tasks:
    # Task to loop over a list of SNMP servers
    - name: Loop over a list
      ansible.builtin.debug:
        msg: "Router {{ hostname }} with SNMP Server {{ item }}"
      loop: "{{ snmp_servers }}"

    # Task to loop over a dictionary of users
    - name: Loop over a dictionary
      ansible.builtin.debug:
        msg: "Switch {{ hostname }} with username {{ item.key }} and password {{ item.value }}"
      with_dict: "{{ users }}"
