---
- name: PLAYBOOK-1
  hosts: all
  tasks:
    - name: Capture output
      ansible.builtin.command:
        cmd: cat ~/res.txt
      register: output
      changed_when: false

    - name: Show output
      ansible.builtin.debug:
        msg: "{{ output.stdout_lines }}"
