---
- name: PLAYBOOK-1
  hosts: all
  tasks:
    - name: A UNAME???
      ansible.builtin.shell: uname -a > ~/res.txt
      changed_when: false

    - name: A WHOAMI???
      ansible.builtin.shell: whoami >> ~/res.txt
      changed_when: false
