---
- name: "Play: save config and take backup" 
  hosts: all
  gather_facts: false
  tasks:
    - name: copy run config to startup 
      ios_command:
        commands: wr
      register: output

    - name: show run 
      ios_command:
        commands: show run 
      register: config  

    - name: save output to backup folder 
      copy: 
        content: "{{ config.stdout[0] }}"
        dest: "./configuration/backup/show_run_{{ inventory_hostname.lower() }}.txt" 
